[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
anchor-client = { version = "0.27.0", features = ["debug"] }
anchor-lang = "0.27.0"
solana-sdk = "1.15.2"
once_cell = "1.17.1"